site_author: Volo support@volo.co.nz
site_name: Volo Provider Documentation
site_dir: mike-site
site_url: https://tf.volo-global.com/v1/providers/volo/volocloud/
copyright: Copyright 2025 Volo
theme:
  name: material
  nav_depth: 1
  logo: assets/Volo_widerV_TextWhite.svg
  favicon: assets/volo_favicon.png

  plugins:
    - search
    - mike:
        alias_type: symlink
        redirect_template: null
        deploy_prefix: ""
        canonical_version: null
        version_selector: true
        css_dir: css
        javascript_dir: js

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light blue
      accent: deep orange

extra:
  version:
    provider: mike

  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/volotechnologies/

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      toc_depth: 3
